"""
engine/schemas.py — Category field schemas for the Smart Modeling Engine.

Each schema defines the fields to extract for a given category,
along with their types and descriptions for LLM prompt construction.
"""

CATEGORY_SCHEMAS = {
    "Fuel": {
        "category": {"type": "string", "description": "Always 'Fuel'", "required": True},
        "expense_date": {"type": "string", "description": "Date of transaction in YYYY-MM-DD format", "required": True},
        "amount": {"type": "number", "description": "Total amount paid in INR (₹). This is the final/grand total.", "required": True},
        "vendor": {"type": "string", "description": "Name of the fuel station or company (e.g., 'HP Petroleum', 'Indian Oil')", "required": True},
        "petrol_pump": {"type": "string", "description": "Brand of the petrol pump (HPCL, BPCL, Indian Oil, Nayara, Shell, etc.)"},
        "liters": {"type": "number", "description": "Volume of fuel in liters"},
        "rate_per_liter": {"type": "number", "description": "Price per liter in INR"},
        "registration_no": {"type": "string", "description": "Vehicle registration number (e.g., MH12AB1234, CG12AP7496)"},
        "odometer": {"type": "integer", "description": "Odometer/mileage reading in km"},
        "location": {"type": "string", "description": "City or location of the fuel station"},
        "invoice_number": {"type": "string", "description": "Bill/receipt/invoice number"},
        "contact_number": {"type": "string", "description": "Phone number on the receipt"},
    },
    "Maintenance": {
        "category": {"type": "string", "description": "Always 'Maintenance'", "required": True},
        "expense_date": {"type": "string", "description": "Date of service in YYYY-MM-DD format", "required": True},
        "amount": {"type": "number", "description": "Total amount paid in INR (₹). Grand total / net payable.", "required": True},
        "vendor": {"type": "string", "description": "Name of the workshop, garage, or service center", "required": True},
        "registration_no": {"type": "string", "description": "Vehicle registration number"},
        "odometer": {"type": "integer", "description": "Odometer reading in km"},
        "location": {"type": "string", "description": "City or location of the service center"},
        "service_type": {"type": "string", "description": "Type of service (e.g., 'Periodic Maintenance', 'General Repair', 'Oil Change')"},
        "invoice_number": {"type": "string", "description": "Invoice/bill/job number"},
        "taxable_amount": {"type": "number", "description": "Subtotal before tax"},
        "non_taxable_amount": {"type": "number", "description": "Non-taxable portion of the bill"},
        "gst_percentage": {"type": "number", "description": "GST rate (e.g., 18 for 18%)"},
        "gst_amount": {"type": "number", "description": "Total GST/tax amount"},
        "gst_invoicing_type": {"type": "string", "description": "Type of GST invoice (e.g., 'Tax Invoice', 'Bill of Supply')"},
        "paid_to": {"type": "string", "description": "Payee name (vendor/workshop name)"},
        "contact_number": {"type": "string", "description": "Phone number on the invoice"},
    },
    "Vehicle": {
        "category": {"type": "string", "description": "Always 'Vehicle'", "required": True},
        "expense_date": {"type": "string", "description": "Date in YYYY-MM-DD format", "required": True},
        "amount": {"type": "number", "description": "Total amount paid in INR (₹)", "required": True},
        "registration_no": {"type": "string", "description": "Vehicle registration number"},
        "location": {"type": "string", "description": "City or location"},
        "challan_no": {"type": "string", "description": "Challan/ticket number"},
        "challan_type": {"type": "string", "description": "Type of challan (e.g., 'Traffic', 'Parking', 'Toll')"},
        "violation_type": {"type": "string", "description": "Type of violation if applicable"},
        "issued_by": {"type": "string", "description": "Authority that issued the challan"},
        "due_date": {"type": "string", "description": "Due date for payment in YYYY-MM-DD format"},
        "parking_location": {"type": "string", "description": "Parking location if parking receipt"},
        "toll_charges": {"type": "number", "description": "Toll charges amount"},
        "parking_charges": {"type": "number", "description": "Parking charges amount"},
        "other_charges": {"type": "number", "description": "Any other charges"},
        "gst_percentage": {"type": "number", "description": "GST rate if applicable"},
        "gst_amount": {"type": "number", "description": "GST amount if applicable"},
        "tds_percentage": {"type": "number", "description": "TDS rate if applicable"},
        "tds_amount": {"type": "number", "description": "TDS amount if applicable"},
        "service_type": {"type": "string", "description": "Type of vehicle service (toll, parking, challan, etc.)"},
        "invoice_number": {"type": "string", "description": "Receipt/ticket number"},
        "contact_number": {"type": "string", "description": "Contact number"},
        "paid_to": {"type": "string", "description": "Payee name"},
    },
    "Other": {
        "category": {"type": "string", "description": "Always 'Other'", "required": True},
        "expense_date": {"type": "string", "description": "Date in YYYY-MM-DD format", "required": True},
        "amount": {"type": "number", "description": "Total amount paid in INR (₹)", "required": True},
        "registration_no": {"type": "string", "description": "Vehicle registration number if visible"},
        "location": {"type": "string", "description": "City or location"},
        "party_type": {"type": "string", "description": "Type of party (e.g., 'Vendor', 'Customer')"},
        "party": {"type": "string", "description": "Name of the party/vendor"},
        "expense_name": {"type": "string", "description": "Name/description of the expense"},
        "invoice_number": {"type": "string", "description": "Invoice/bill number"},
        "contact_number": {"type": "string", "description": "Phone number"},
        "paid_to": {"type": "string", "description": "Payee name"},
    },
}
